// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83_pI4FyvuawLmxHqb_AMGqPq2JD9tNg',
    appId: '1:793951472222:web:a2efcc50ab89139b75c2cf',
    messagingSenderId: '793951472222',
    projectId: 'health-care-125d8',
    authDomain: 'health-care-125d8.firebaseapp.com',
    storageBucket: 'health-care-125d8.firebasestorage.app',
    measurementId: 'G-TSW75373J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Bt6evttrujbYgqfZPkHaD0LYPNLRX1g',
    appId: '1:793951472222:android:24c09cff86acf35175c2cf',
    messagingSenderId: '793951472222',
    projectId: 'health-care-125d8',
    storageBucket: 'health-care-125d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjleVtfdqum4Fmybn_7RoXi2PE3fb8CO8',
    appId: '1:793951472222:ios:993ebafcb2f1c5b175c2cf',
    messagingSenderId: '793951472222',
    projectId: 'health-care-125d8',
    storageBucket: 'health-care-125d8.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjleVtfdqum4Fmybn_7RoXi2PE3fb8CO8',
    appId: '1:793951472222:ios:993ebafcb2f1c5b175c2cf',
    messagingSenderId: '793951472222',
    projectId: 'health-care-125d8',
    storageBucket: 'health-care-125d8.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC83_pI4FyvuawLmxHqb_AMGqPq2JD9tNg',
    appId: '1:793951472222:web:fd19b02516e78bee75c2cf',
    messagingSenderId: '793951472222',
    projectId: 'health-care-125d8',
    authDomain: 'health-care-125d8.firebaseapp.com',
    storageBucket: 'health-care-125d8.firebasestorage.app',
    measurementId: 'G-SSZBTXSTS4',
  );
}
